<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?php 

$this->form->setAttribute("action", $this->url('helpdesk/add'));
$this->form->setAttribute("method", "post");

$form = $this->form;

$form->prepare();

echo $this->form()->openTag($form);
?>
<h3>Add New Helpdesk Ticket</h3>
<?php
	   $message = $this->message;
	   if ($message == true) {
		$result='<div class="alert alert-success">Thank You! Ticket Created</div>';
		}
		else{
			if($message == null) {
			$result='';
			}else{
				$result = '<div class="alert alert-danger">Sorry there was an error creating a ticket. Please try again later</div>';
		}}
	   
	?>
<div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <?php echo $result; ?>    
        </div>
    </div>	
<div><br/></div>
<div class="form-group row">
	<?php
	   $enteredby = $form->get("ENTERED_BY");
	?>
	<div class="col-sm-2 col-md-2">
		<?= $this->formLabel($enteredby) ?>
	</div>
	<div class="col-sm-10 col-md-10">
		<?= $this->formElement($enteredby) ?>
		<?= $this->formElementErrors()->render($enteredby, ["class" => "helper-block"]) ?>
	</div>
	
	
</div>
<div class="form-group row">
	<?php 
	   $priorityid = $form->get("PRIORITY_ID");
	?>
	<div class="col-sm-2 col-md-2">
		<?= $this->formLabel($priorityid) ?>
	</div>
	<div class="col-sm-10 col-md-10">
		<?= $this->formElement($priorityid) ?>
		<?= $this->formElementErrors()->render($priorityid, ["class" => "helper-block"]) ?>
	</div>
</div>
<div class="form-group row">
	<?php 
	   $locationid = $form->get("LOCATION_ID");
	?>
	<div class="col-sm-2 col-md-2">
		<?= $this->formLabel($locationid) ?>
	</div>
	<div class="col-sm-4 col-md-4">
		<?= $this->formElement($locationid) ?>
		<?= $this->formElementErrors()->render($locationid, ["class" => "helper-block"]) ?>
	</div>
	
	<?php 
	   $vehiclenumber = $form->get("VEHICLE_NUMBER");
	?>
	<div class="col-sm-2 col-md-2">
		<?= $this->formLabel($vehiclenumber) ?>
	</div>
	<div class="col-sm-4 col-md-4">
		<?= $this->formElement($vehiclenumber) ?>
		<?= $this->formElementErrors()->render($vehiclenumber, ["class" => "helper-block"]) ?>
	</div>
</div>
<div class="form-group row">
	<?php 
	   $problemtypeid = $form->get("PROBLEM_TYPE_ID");
	?>
	<div class="col-sm-2 col-md-2">
		<?= $this->formLabel($problemtypeid) ?>
	</div>
	<div class="col-sm-10 col-md-10">
		<?= $this->formElement($problemtypeid) ?>
		<?= $this->formElementErrors()->render($problemtypeid, ["class" => "helper-block"]) ?>
	</div>
</div>
<div class="form-group row">
	<?php 
	   $problemdescription = $form->get("PROBLEM_DESCRIPTION");
	?>
	<div class="col-sm-2 col-md-2">
		<?= $this->formLabel($problemdescription) ?>
	</div>
	<div class="col-sm-10 col-md-10">
		<?= $this->formElement($problemdescription) ?>
		<?= $this->formElementErrors()->render($problemdescription, ["class" => "helper-block"]) ?>
	</div>
</div>
<div><br/></div>
<div class="form-group row">
	<div class="col-sm-12 col-md-12" style="text-align: center;"><?= $this->formElement($form->get("Submit")) ?></div>
</div>


<?= $this->form()->closeTag() ?>